### ISSUE TITLE
Could you/we add an option to use 256 color?

### ISSUE THREAD

**Issue by marcosps** [tyrannicaltoucan/vim-quantum#5]
tmux doesn't handle too well true color schemes on VIM, but quantum is the best scheme that I found so far.

Do you have plans to add an option to toggle between true color and 256 color?

Thanks!

**Comment by tyrannicaltoucan** [comment]
Sure! I originally created a 256 color version of Quantum, but removed it because it was very disorganized and confusing (`quantum.vim` technically holds two color schemes, and both had very similar 256 color variants).

The simplest way I can re-implement a 256 version of Quantum:
* `quantum.vim` containing both the `quantum` and `quantum-black` true color schemes
* `quantum-256.vim` containing a singular 256 color optimized version of `quantum-black`

I will keep this issue open in case you or someone has a better idea or implementation.

**Comment by marcosps** [comment]
For me, it's perfect. I never played with vim colors before, but I can take a look on it and help you! Or, if you think you can do it, better yet :)

Thanks!

**Comment by dylnmc** [comment]
:+1: for *-256color support. I'd help. Looks like good theme.

I like working in urxvt so this would be nice.

**Comment by marcosps** [comment]
Closing old bugs...
